# Generated by Django 2.1.4 on 2019-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23)),
                ('phone', models.CharField(max_length=23)),
                ('adder', models.CharField(max_length=23)),
            ],
        ),
    ]
