# Generated by Django 2.1.4 on 2019-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190416_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
